language: java
jdk: oraclejdk8

cache:
  directories:
    - node_modules
    - $HOME/.m2

services:
  - mysql
 # - neo4j

before_install:
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql -h "localhost" -u "root" "gutenberg" < "DBSetup.sql"
  - mysql -u root -e "CREATE USER 'testUser'@'localhost' IDENTIFIED BY 'testUser';"
  - mysql -u root -e "GRANT ALL ON gutenberg.* TO 'testUser'@'localhost';"


script:
  - mvn verify

after_success:
  - surge --project ./target/site --domain cheesy.surge.sh
after_failure:
  #Remove documentation for a failing project
  - surge teardown cheesy.surge.sh
