language: java
jdk: oraclejdk8

cache:
  directories:
    - node_modules
    - $HOME/.m2

services:
  - mysql
#  - neo4j

before_install:
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql -h "127.0.0.1" -u "root" "-proot" "gutenberg" < "TravisSQL.sql"

script:
  - mvn verify

after_success:
  - surge --project ./target/site --domain cheesy.surge.sh
after_failure:
  #Remove documentation for a failing project
  - surge teardown cheesy.surge.sh
