language: java
jdk: oraclejdk8

cache:
  directories:
    - node_modules
    - $HOME/.m2

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql -h "localhost" -u "root" "gutenberg" < "DBSetup.sql"
  - mysql -h "localhost" -u "root" "gutenberg" < "procedures.sql"
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root')"

  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start

  # install newman
  - npm install -g update-node
  - npm install newman --global;

script:
  - mvn verify
  - newman run postman_test.json -e postman_environment.json


after_success:
  - surge --project ./target/site --domain cheesy.surge.sh
after_failure:
  #Remove documentation for a failing project
  - surge teardown cheesy.surge.sh
