language: java
jdk: oraclejdk8

cache:
  directories:
    - node_modules
    - $HOME/.m2

services:
  - mysql
#  - neo4j

before_install:
  - mysql -e 'CREATE DATABASE gutenberg;'

script:
  - mvn verify

after_success:
  - surge --project ./target/site --domain cheesy.surge.sh
after_failure:
  #Remove documentation for a failing project
  - surge teardown cheesy.surge.sh
